/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: { DEFAULT: "#000000", hover: "#2a2a2a", light: "#f5f5f5" },
        surface: "#FDF8F8",
        background: "#FDF8F8",
        foreground: "#1C1B1B",
        muted: { DEFAULT: "#747878", soft: "#A8A8A8" },
        border: "#E5E2E1",
        outline: "#747878",
        "outline-variant": "#C4C7C7",
        "surface-variant": "#E5E2E1",
        "surface-container-low": "#F7F3F2",
        "surface-container": "#F1EDEC",
        "surface-container-high": "#EBE7E6",
        "surface-container-highest": "#E5E2E1",
        "surface-dim": "#DDD9D8",
        "surface-bright": "#FDF8F8",
        "surface-container-lowest": "#FFFFFF",
        "on-surface": "#1C1B1B",
        "on-surface-variant": "#444748",
        "inverse-on-surface": "#F4F0EF",
        "inverse-surface": "#313030",
        error: "#BA1A1A",
        "error-container": "#FFDAD6",
        "on-error": "#FFFFFF",
        "on-error-container": "#93000A",
        secondary: "#4648D4",
        "secondary-container": "#6063EE",
        "on-secondary": "#FFFFFF",
        "on-secondary-container": "#FFFBFF",
        "secondary-fixed": "#E1E0FF",
        "secondary-fixed-dim": "#C0C1FF",
        "on-secondary-fixed": "#07006C",
        "on-secondary-fixed-variant": "#2F2EBE",
        tertiary: "#000000",
        "tertiary-container": "#1C1B1A",
        "on-tertiary": "#FFFFFF",
        "on-tertiary-container": "#868381",
        "tertiary-fixed": "#E6E1DF",
        "tertiary-fixed-dim": "#CAC6C3",
        "on-tertiary-fixed": "#1C1B1A",
        "on-tertiary-fixed-variant": "#484645",
        "primary-fixed": "#E5E2E1",
        "primary-fixed-dim": "#C8C6C5",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#858383",
        "on-primary-fixed": "#1C1B1B",
        "on-primary-fixed-variant": "#474646",
        "surface-tint": "#5F5E5E",
        "inverse-primary": "#C8C6C5",
      },
      borderRadius: {
        sm: "2px",
        DEFAULT: "2px",
        md: "4px",
        lg: "4px",
        xl: "8px",
        "2xl": "12px",
        full: "12px",
      },
      fontFamily: {
        display: ["Inter", "system-ui", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["Geist", "system-ui", "sans-serif"],
      },
      fontSize: {
        "metric-display": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "metric-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      spacing: {
        "margin-desktop": "40px",
        "margin-mobile": "20px",
        gutter: "16px",
        unit: "4px",
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};